### ISSUE TITLE
MB4DLZ and MB02SZ use a non Standard BLAS routine

### ISSUE THREAD

**Issue by grisuthedragon** [SLICOT/SLICOT-Reference#12]
The routines MB4DLZ and MB02SZ  reference the DCABS1 routine, which is not available in some BLAS implementations(like ATLAS). In order to get SLICOT working with allmost all BLAS libraries, this routine needs to be replaced or inlined.

**Comment by VasileSima4** [comment]
MB4DLZ and MB02SZ  have been updated in Version v5.9 and there are no more DCABS1 calls.
