### ISSUE TITLE
Inclusion of AB13HD method for L-infinity norm computation of Descriptor Systems

### ISSUE THREAD

**Issue by Algopaul** [SLICOT/SLICOT-Reference#5]
The function `AB13HD` (available, e.g., [here](https://www.math.tu-berlin.de/fachgebiete_ag_modnumdiff/fg_numerische_mathematik/v_menue/mitarbeiterinnen/matthias_voigt/software/l_norm_fuer_deskriptorsysteme/parameter/en/)) written by @VasileSima4  and Matthias Voigt is currently not included in this repository.
However, `AB13HD` is needed for computing the L-infinity norm, when the `E` matrix (in an `EABCD`-system) is singular. The function `AB13DD`, that is currently available, assumes that `E` is nonsingular.
Is it possible to include `AB13HD` into the SLICOT-Reference repository? In this way it would also be automatically available e.g. to julia users via [SLICOT_jll](https://github.com/JuliaBinaryWrappers/SLICOT_jll.jl).
Can we just open a pull-request with the code from this [link](https://www.math.tu-berlin.de/fachgebiete_ag_modnumdiff/fg_numerische_mathematik/v_menue/mitarbeiterinnen/matthias_voigt/software/l_norm_fuer_deskriptorsysteme/parameter/en/) or is further testing/documentation needed?

**Comment by VasileSima4** [comment]
I will do some further testing of AB13HD in the next few weeks, and then add it to the SLICOT-Reference repository.  

Vasile Sima
