### ISSUE TITLE
make.inc is missing

### ISSUE THREAD

**Issue by thierry-FreeBSD** [SLICOT/SLICOT-Reference#6]
The provided makefiles include make.inc, but it is not in this repository.

Here is an old one (from SLICOT-5.0): 
[make.inc](https://github.com/SLICOT/SLICOT-Reference/files/10131614/make.inc.txt)
(to be renamed without .txt, but GH does not accept .inc files)

Of course it must be configured!

The file Installation.txt is also missing: 
[Installation.txt](https://github.com/SLICOT/SLICOT-Reference/files/10131631/Installation.txt)

**Comment by VasileSima4** [comment]
makefiles for Windows and Linux have been added in December 2022.
